language: python
python:
    - "2.7"
env:
    - TOX_ENV=docs
    - TOX_ENV=flake8
    - TOX_ENV=py26
    - TOX_ENV=py27
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
notifications:
    flowdock: a73d66c41c6e4406e1c47e042dfd2b59
