language: python
python:
- '2.7'
env:
- TOX_ENV=docs
- TOX_ENV=flake8
- TOX_ENV=py27
- TOX_ENV=py26
install:
- pip install tox
script:
- tox -e $TOX_ENV
deploy:
- provider: pypi
  server: https://pypi.python.org/pypi
  on:
    branch: pypi-release
    condition: $TOX_ENV = py27
  user: cosmo-maint
  password:
    secure: "J72KNbKIbVPJlmom7yNfwH4EFCzH94teKhdTSUu6BJeLpVJltm97+5UYqPNmpmnrs4Q8Kk3agoLPsC9Bc6mzxD7Wd7RguqCFZ1zp+Cf4nUqyvOnL5RimI2bqpnimpvN4+wDfuYxS//Na2qfk2Q41RoYT3/ix/GpcuT2kLr212kQ="
- provider: pypi
  server: https://testpypi.python.org/pypi
  on:
    branch: pypi-test
    condition: $TOX_ENV = py27
  user: cosmo-maint
  password:
    secure: "N/+qRTceUUvVXuftDjbggy4cgRaLtV8On1b69RjYoub46wbUDa6ufKQ4dEtIHbhHVvnY4Cv+b0dCOA4Z9gG8YlFesqdp1iJ8vuXIi+ymdfJMShbA6gWqj8CRyd4gsMBHn67DOjX1bkVySRlavMjrII/sp1zjDI8we+/wm7edIBY="
after_deploy:
- git clone https://github.com/cloudify-cosmo/travis-utils.git
- python travis-utils/validate_pypi.py -v -b $TRAVIS_BRANCH || exit 1
notifications:
  flowdock: a73d66c41c6e4406e1c47e042dfd2b59
